sudo: false
language: node_js
node_js:
  - "4.0"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - make install;
script:
  - make test-ci;
after_success:
  - npm install coveralls@2.10.0 && cat .report/coverage/lcov/lcov.info | coveralls