/**
 * @description - collection action types
 * @type {string}
 */
export const REMOTE_COLLECTION = 'REMOTE_COLLECTION';
export const REMOTE_COLLECTION_SUCCESS = 'REMOTE_COLLECTION_SUCCESS';
export const REMOTE_COLLECTION_ERROR = 'REMOTE_COLLECTION_ERROR';
export const REMOTE_COLLECTION_TYPES = [
  REMOTE_COLLECTION,
  REMOTE_COLLECTION_SUCCESS,
  REMOTE_COLLECTION_ERROR
];
